name: Docker Image CI

on:
  push:
    branches: [ bullseye ]
  pull_request:
    branches: [ bullseye ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: username/my-repo
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
